[platformio]
default_envs = voxonebt

[env:voxonebt]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.app_partition_name = app
lib_deps =
    git+https://github.com/pschatzmann/ESP32-A2DP.git#v1.8.11
build_flags =
    -DCORE_DEBUG_LEVEL=0
