[platformio]
default_envs = desk

[env]
platform = platformio/espressif32@6.12.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = spiffs
board_build.partitions = partitions_yoradio.csv

extra_scripts =
    pre:scripts/patch_glcdfont.py
    post:scripts/versioned_artifacts.py

lib_deps =
    adafruit/Adafruit GFX Library@1.12.6
    adafruit/Adafruit BusIO@1.17.4
    adafruit/Adafruit ST7735 and ST7789 Library@1.11.0
    adafruit/Adafruit seesaw Library@1.7.9

[env:desk]
board = esp32dev
build_flags =
    -DYOVOXONE_PROFILE_DESK=1

[env:din]
board = esp32-s3-devkitc-1
build_flags =
    -DYOVOXONE_PROFILE_DIN=1

[env:salon]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    -DBOARD_HAS_PSRAM
    -DYOVOXONE_PROFILE_SALON=1

[env:salon_dsp]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    -DBOARD_HAS_PSRAM
    -DYOVOXONE_PROFILE_SALON_DSP=1
