#ifndef VOXONE_PROFILE_B0_H
#define VOXONE_PROFILE_B0_H

#define VOXONE_PROFILE_NAME "B0"
#define VOXONE_PROFILE_MCU voxone::Mcu::Esp32S3
#define VOXONE_PROFILE_DISPLAY voxone::Display::None
#define VOXONE_DISPLAY_PROFILE VOXONE_DISPLAY_PROFILE_NONE
#define VOXONE_DISPLAY_CONTROLLER VOXONE_DISPLAY_CONTROLLER_NONE
#define VOXONE_PROFILE_AUDIO voxone::AudioOutput::Pcm5102a

#define VOXONE_HAS_DISPLAY 0
#define VOXONE_HAS_ENCODER 0
#define VOXONE_HAS_VU 0
#define VOXONE_HAS_BT 1
#define VOXONE_HAS_AUX 0
#define VOXONE_HAS_SPDIF 0
#define VOXONE_HAS_TDA7719 false
#define VOXONE_HAS_LOCAL_UI 0
#define VOXONE_PIN_MAP_COMPLETE 1

#define DSP_MODEL DSP_DUMMY

#define I2S_BCLK 1
#define I2S_DOUT 2
#define I2S_LRC 3

// VoxOneBT I2S RX remains reserved; its UART pins are active in BtLink.
#define VOXONE_BT_I2S_BCLK_IN_PIN 4
#define VOXONE_BT_I2S_WS_IN_PIN 5
#define VOXONE_BT_I2S_DATA_IN_PIN 6
#define VOXONE_BT_I2S_BCLK_PIN VOXONE_BT_I2S_BCLK_IN_PIN
#define VOXONE_BT_I2S_WS_PIN VOXONE_BT_I2S_WS_IN_PIN
#define VOXONE_BT_I2S_DATA_PIN VOXONE_BT_I2S_DATA_IN_PIN
#define VOXONE_BT_UART_RX_PIN 7
#define VOXONE_BT_UART_TX_PIN 8

#endif
